### ISSUE TITLE
Race condition when directory contents change?

### ISSUE THREAD

**Issue by nferch** [letorbi/inotifyrecursive#13]
I'm running up against what I assume is some sort of race condition:

`
2021-01-31 00:45:39,906 ERROR An uncaught exception occurred
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/synoindexwatcher/__main__.py", line 218, in <module>
    start()
  File "/usr/lib/python2.7/site-packages/synoindexwatcher/__main__.py", line 193, in start
    for event in inotify.read():
  File "/usr/lib/python2.7/site-packages/inotifyrecursive/inotifyrecursive.py", line 149, in read
    moved_from[event.cookie] = info["children"][event.name]
KeyError: 'MOVED_DIR'
`

I suspect MOVED_DIR is being moved while the directory is being traversed.

**Comment by letorbi** [comment]
Thanks for the bug report. Do you know a way how to reproduce the error? I know this is often not possible for race conditions, but it would make life easier for me :)

However, I will take a look at it in any case, but it might take some time, since I'm quite busy with RL right now.

**Comment by nferch** [comment]
I don't have a test case or the like to share, but it happens pretty regularly with my 
SABnzbd/Sonarr downloads so I don't think it'd be too hard to generate one.

Mostly just wanted to get this out there to see if you or other had seen similar issues, I can try and dig in a little more as time permits. I might also try a naive solution of making a copy of the `read()` result or ignoring the exception, haven't dug too much into the code to see what it's doing.

**Comment by letorbi** [comment]
Ok, thanks for the info. I'll start debugging as soon as I can spare some time.

Would be great, if you find some time to dig deeper into the issue :)

**Comment by nferch** [comment]
The following patch keeps it from crashing, I haven't looked into whether it's succeeding in doing the job of reindexing. Running with debug mode now so I can investigate further.

```
diff --git a/inotifyrecursive/inotifyrecursive.py b/inotifyrecursive/inotifyrecursive.py
index a71e622..f553bc6 100644
--- a/inotifyrecursive/inotifyrecursive.py
+++ b/inotifyrecursive/inotifyrecursive.py
@@ -146,7 +146,11 @@ class INotify(inotify_simple.INotify):
                         if event.mask & flags.MOVED_TO and event.cookie in moved_from:
                             del moved_from[event.cookie]
                     elif event.mask & flags.MOVED_FROM:
-                        moved_from[event.cookie] = info["children"][event.name]
+                        try:
+                            moved_from[event.cookie] = info["children"][event.name]
+                        except KeyError:
+                            logging.debug("%s no longer present in %s" % (event.name, info["children"]))
+                            pass
                 elif event.mask & flags.IGNORED:
                     self.__clr_info(event.wd)
                 if (event.mask & mask):
```
