### ISSUE TITLE
Obtain full path to file in subdirectory

### ISSUE THREAD

**Issue by tehkillerbee** [letorbi/inotifyrecursive#16]
I noticed that the event only returns the filename and not the full path including parent and subdirectories. Is there a way to obtain the path including the watch directory and subdirectories?

**Comment by tehkillerbee** [comment]
Currently, I monitor a directory named "monitor". Within this directory, a directory "testimg" is created. Inside this dir, an image is created. The events does not describe that the created image is stored within testimg. Do you have any suggestions on how to get the full path to the image?

Below is a code snippet and the events generated when running the program

```
# watch selected directory, save processed output in subdir until process is killed
inotify = INotify()
watch_flags = flags.CREATE | flags.DELETE | flags.MODIFY | flags.DELETE_SELF
#wd = inotify.add_watch(args.input, watch_flags)
wd = inotify.add_watch_recursive(args.input, watch_flags, filter=None)

while True:
    time.sleep(0.25)
    for event in inotify.read():
        print(event)
        for flag in flags.from_mask(event.mask):
            print('    ' + str(flag))
```

Event(wd=1, mask=1073742080, cookie=0, name='testimg')
    flags.CREATE
    flags.ISDIR
Event(wd=2, mask=256, cookie=0, name='imageA009.png')
    flags.CREATE
Event(wd=2, mask=2, cookie=0, name='imageA009.png')
    flags.MODIFY

**Comment by letorbi** [comment]
Have you tried the `inotify.get_path(wd)` function? You should be able to determine the full path by adding the following line to the `for event in ...` loop body:

```
fullpath = inotify.get_path(event.wd) + event.name
```

I have not tested the code, but I think it shows enough to get the idea :)

**Comment by tehkillerbee** [comment]
Thanks for the suggestion. Yes that does seem to work as expected.
